"""empty message

Revision ID: c32c1a66808b
Revises: 768b6b5afa5a
Create Date: 2019-07-05 01:08:14.505118

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c32c1a66808b'
down_revision = '768b6b5afa5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sm_stock_para')
    op.drop_table('sm_user_role')
    op.drop_table('sm_user_member')
    op.drop_table('sm_user_log')
    op.drop_table('sm_user_agent')
    op.drop_table('sm_clerk')
    op.drop_table('sm_agent_drawing')
    op.drop_table('sm_buy_trade')
    op.drop_table('sm_manual_trade')
    op.drop_table('sm_trade_bill')
    op.drop_table('sm_user')
    op.drop_table('sm_close_plan')
    op.drop_table('sm_sys_notice')
    op.drop_table('sm_user_admin')
    op.drop_table('sm_sell_trade')
    op.drop_table('sm_member_drawing')
    op.drop_table('sm_recharge')
    op.drop_table('sm_sys_conf')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sm_sys_conf',
    sa.Column('Key', mysql.VARCHAR(length=100), nullable=False, comment='配置的键值'),
    sa.Column('Value', mysql.VARCHAR(length=255), nullable=False, comment='值'),
    sa.Column('Description', mysql.VARCHAR(length=255), nullable=True, comment='描述'),
    sa.PrimaryKeyConstraint('Key'),
    comment='系统配置表',
    mysql_comment='系统配置表',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('sm_recharge',
    sa.Column('Number', mysql.VARCHAR(length=50), nullable=False, comment='订单号'),
    sa.Column('MemberID', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=True, comment='参与者'),
    sa.Column('Value', mysql.DOUBLE(asdecimal=True), nullable=True, comment='充值金额'),
    sa.Column('OrderIP', mysql.VARCHAR(length=30), nullable=True, comment='下单的IP'),
    sa.Column('CreateTime', mysql.DATETIME(), nullable=True),
    sa.Column('SNumber', mysql.VARCHAR(length=50), nullable=True, comment='流水号'),
    sa.Column('VendorNumber', mysql.VARCHAR(length=50), nullable=True, comment='商家号'),
    sa.Column('Bank', mysql.VARCHAR(length=50), nullable=True, comment='银行'),
    sa.Column('DepositIP', mysql.VARCHAR(length=30), nullable=True, comment='存款IP'),
    sa.Column('DepositTime', mysql.DATETIME(), nullable=True),
    sa.Column('DepositStatus', mysql.VARCHAR(length=50), nullable=True, comment='存款状态'),
    sa.Column('Note', mysql.VARCHAR(length=255), nullable=True, comment='备注'),
    sa.ForeignKeyConstraint(['MemberID'], ['sm_user_member.ID'], name='FK_Reference_16'),
    sa.PrimaryKeyConstraint('Number'),
    comment='充值管理表',
    mysql_comment='充值管理表',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('sm_member_drawing',
    sa.Column('ID', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=True, nullable=False, comment='会员提款ID'),
    sa.Column('MemberID', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=False, comment='会员ID'),
    sa.Column('DrawingTime', mysql.DATETIME(), nullable=True),
    sa.Column('DrawingValue', mysql.DOUBLE(asdecimal=True), nullable=False, comment='提款金额'),
    sa.Column('Bank', mysql.VARCHAR(length=50), nullable=True, comment='银行'),
    sa.Column('BankOfDeposit', mysql.VARCHAR(length=50), nullable=True, comment='开户行'),
    sa.Column('BankAccountName', mysql.VARCHAR(length=20), nullable=True, comment='账户名'),
    sa.Column('BankAccount', mysql.VARCHAR(length=50), nullable=False, comment='银行账户'),
    sa.Column('DrawingStatus', mysql.INTEGER(display_width=5), autoincrement=False, nullable=False, comment='提款状态'),
    sa.Column('ChangeTime', mysql.DATETIME(), nullable=True),
    sa.Column('Note', mysql.VARCHAR(length=255), nullable=True, comment='备注'),
    sa.ForeignKeyConstraint(['MemberID'], ['sm_user_member.ID'], name='FK_Reference_18'),
    sa.PrimaryKeyConstraint('ID'),
    comment='会员提款表',
    mysql_comment='会员提款表',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('sm_sell_trade',
    sa.Column('ID', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=True, nullable=False, comment='平仓ID'),
    sa.Column('MemberID', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=True, comment='会员ID'),
    sa.Column('TickerSymbol', mysql.VARCHAR(length=30), nullable=False, comment='股票代码'),
    sa.Column('BuyNumber', mysql.VARCHAR(length=30), nullable=False, comment='购买单号'),
    sa.Column('BuyTime', mysql.DATETIME(), nullable=False),
    sa.Column('BuyPrice', mysql.DOUBLE(asdecimal=True), nullable=False, comment='购买价格'),
    sa.Column('SellNumber', mysql.VARCHAR(length=30), nullable=False, comment='售出编码'),
    sa.Column('SellTime', mysql.DATETIME(), nullable=False),
    sa.Column('SellPrice', mysql.DOUBLE(asdecimal=True), nullable=False, comment='售出价格'),
    sa.Column('BuyType', mysql.INTEGER(display_width=5, unsigned=True), autoincrement=False, nullable=False, comment='购买类型（多/空）'),
    sa.Column('Fee', mysql.DOUBLE(asdecimal=True), nullable=False, comment='手续费'),
    sa.Column('Interest', mysql.DOUBLE(asdecimal=True), nullable=False, comment='融资利息'),
    sa.Column('StampDuty', mysql.DOUBLE(asdecimal=True), nullable=False, comment='印花税'),
    sa.Column('Profit', mysql.DOUBLE(asdecimal=True), nullable=False, comment='收益'),
    sa.ForeignKeyConstraint(['MemberID'], ['sm_user_member.ID'], name='FK_Reference_9', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('ID'),
    comment='用户平仓表',
    mysql_comment='用户平仓表',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('sm_user_admin',
    sa.Column('ID', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=False, comment='管理员ID'),
    sa.ForeignKeyConstraint(['ID'], ['sm_user.ID'], name='FK_Reference_1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ID'),
    comment='管理员表',
    mysql_comment='管理员表',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('sm_sys_notice',
    sa.Column('ID', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=True, nullable=False, comment='公告编号'),
    sa.Column('CreatorID', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=True, comment='创建者ID'),
    sa.Column('Title', mysql.VARCHAR(length=50), nullable=True, comment='标题'),
    sa.Column('Content', mysql.VARCHAR(length=255), nullable=True, comment='内容'),
    sa.Column('Time', mysql.DATETIME(), nullable=False),
    sa.Column('AgentDisable', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='代理不显示'),
    sa.Column('MemberDisable', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='成员不显示'),
    sa.ForeignKeyConstraint(['CreatorID'], ['sm_user_admin.ID'], name='FK_Reference_12', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('ID'),
    comment='系统公告表',
    mysql_comment='系统公告表',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('sm_close_plan',
    sa.Column('ID', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=True, nullable=False, comment='编号'),
    sa.Column('CreatorID', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=True, comment='管理员ID'),
    sa.Column('PlanDate', sa.DATE(), nullable=False, comment='休市日期'),
    sa.Column('Time', mysql.DATETIME(), nullable=False),
    sa.Column('Note', mysql.VARCHAR(length=255), nullable=True, comment='备注'),
    sa.ForeignKeyConstraint(['CreatorID'], ['sm_user_admin.ID'], name='FK_Reference_13', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('ID'),
    comment='休市安排',
    mysql_comment='休市安排',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('sm_user',
    sa.Column('ID', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=True, nullable=False, comment='管理员表ID主键'),
    sa.Column('LoginName', mysql.VARCHAR(length=64), nullable=False, comment='登录名'),
    sa.Column('NickName', mysql.VARCHAR(length=64), nullable=False, comment='昵称'),
    sa.Column('Password', mysql.VARCHAR(length=255), nullable=False, comment='密码'),
    sa.Column('CreateTime', mysql.DATETIME(), nullable=False),
    sa.Column('LastLogonTime', mysql.DATETIME(), nullable=True),
    sa.Column('CreatorID', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=True, comment='创建者ID'),
    sa.Column('Forbidden', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否禁用， 默认不禁用'),
    sa.Column('RoleID', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=True, comment='用户类型ID'),
    sa.ForeignKeyConstraint(['RoleID'], ['sm_user_role.ID'], name='FK_Reference_4'),
    sa.PrimaryKeyConstraint('ID', 'LoginName'),
    comment='用户表',
    mysql_comment='用户表',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('sm_trade_bill',
    sa.Column('ID', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=True, nullable=False, comment='交易账单ID'),
    sa.Column('Number', mysql.VARCHAR(length=30), nullable=False, comment='交易单号'),
    sa.Column('TradeType', mysql.INTEGER(display_width=5, unsigned=True), autoincrement=False, nullable=False, comment='交易类型'),
    sa.Column('MemberID', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=True, comment='会员ID'),
    sa.Column('TickerSymbol', mysql.VARCHAR(length=30), nullable=False, comment='股票代码'),
    sa.Column('TickerName', mysql.VARCHAR(length=30), nullable=False, comment='股票名称'),
    sa.Column('UnitPrice', mysql.DOUBLE(asdecimal=True), nullable=False, comment='单价'),
    sa.Column('Hands', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=False, comment='手数'),
    sa.Column('Amount', mysql.DOUBLE(asdecimal=True), nullable=False, comment='交易金额'),
    sa.Column('Time', mysql.DATETIME(), nullable=False),
    sa.Column('OpID', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=True, comment='操作人'),
    sa.Column('Note', mysql.VARCHAR(length=255), nullable=True, comment='备注'),
    sa.ForeignKeyConstraint(['MemberID'], ['sm_user_member.ID'], name='FK_Reference_10'),
    sa.PrimaryKeyConstraint('ID'),
    comment='交易账单表',
    mysql_comment='交易账单表',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('sm_manual_trade',
    sa.Column('ID', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('MemberID', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=True, comment='会员id'),
    sa.Column('OpType', mysql.VARCHAR(length=20), nullable=True, comment='操作类型'),
    sa.Column('DetailType', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('CreatorID', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=True, comment='管理员ID'),
    sa.Column('CreateTime', mysql.DATETIME(), nullable=True),
    sa.Column('Value', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=False, comment='金额'),
    sa.Column('Note', mysql.VARCHAR(length=255), nullable=True, comment='备注'),
    sa.ForeignKeyConstraint(['CreatorID'], ['sm_user_admin.ID'], name='FK_Reference_15'),
    sa.ForeignKeyConstraint(['MemberID'], ['sm_user_member.ID'], name='FK_Reference_14'),
    sa.PrimaryKeyConstraint('ID'),
    comment='手动入扣款',
    mysql_comment='手动入扣款',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('sm_buy_trade',
    sa.Column('ID', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=True, nullable=False, comment='持仓id'),
    sa.Column('Number', mysql.VARCHAR(length=30), nullable=False, comment='单号'),
    sa.Column('MemberID', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=False, comment='会员ID'),
    sa.Column('TradeTime', mysql.DATETIME(), nullable=False),
    sa.Column('TickerSymbol', mysql.VARCHAR(length=30), nullable=False, comment='股票代码'),
    sa.Column('Price', mysql.DOUBLE(asdecimal=True), nullable=False, comment='购买价格'),
    sa.Column('Hands', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=False, comment='手数'),
    sa.Column('BuyType', mysql.INTEGER(display_width=5, unsigned=True), autoincrement=False, nullable=False, comment='购买类型（多/空）'),
    sa.Column('BuyFeeRate', mysql.DOUBLE(asdecimal=True), nullable=True, comment='买入手续费'),
    sa.Column('StoreFeeRate', mysql.DOUBLE(asdecimal=True), nullable=True, comment='留仓费'),
    sa.Column('RiseFallSpreadRate', mysql.DOUBLE(asdecimal=True), nullable=True, comment='点差费'),
    sa.ForeignKeyConstraint(['MemberID'], ['sm_user_member.ID'], name='FK_Reference_8'),
    sa.PrimaryKeyConstraint('ID'),
    comment='用户持仓表',
    mysql_comment='用户持仓表',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('sm_agent_drawing',
    sa.Column('ID', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=True, nullable=False, comment='提款ID'),
    sa.Column('AgentID', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=False, comment='目标账户ID'),
    sa.Column('DrawingTime', mysql.DATETIME(), nullable=False),
    sa.Column('DrawingValue', mysql.DOUBLE(asdecimal=True), nullable=False, comment='提款金额'),
    sa.Column('Bank', mysql.VARCHAR(length=50), nullable=True, comment='银行'),
    sa.Column('BankOfDeposit', mysql.VARCHAR(length=50), nullable=True, comment='开户行'),
    sa.Column('BankAccount', mysql.VARCHAR(length=50), nullable=False, comment='银行账户'),
    sa.Column('DrawingStatus', mysql.INTEGER(display_width=5), autoincrement=False, nullable=False, comment='提款状态'),
    sa.Column('ChangeTime', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['AgentID'], ['sm_user_agent.ID'], name='FK_Reference_17'),
    sa.PrimaryKeyConstraint('ID'),
    comment='代理提款',
    mysql_comment='代理提款',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('sm_clerk',
    sa.Column('ID', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=True, nullable=False, comment='业务员ID'),
    sa.Column('AgentID', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=False, comment='创建的代理的ID'),
    sa.Column('NickName', mysql.VARCHAR(length=255), nullable=True, comment='名称'),
    sa.Column('Forbidden', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='是否禁用，默认不禁用'),
    sa.ForeignKeyConstraint(['AgentID'], ['sm_user_agent.ID'], name='FK_Reference_5'),
    sa.PrimaryKeyConstraint('ID'),
    comment='业务员表',
    mysql_comment='业务员表',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('sm_user_agent',
    sa.Column('ID', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=False, comment='代理ID'),
    sa.Column('Margin', mysql.DOUBLE(asdecimal=True), nullable=True, comment='保证金'),
    sa.Column('TestMargin', mysql.DOUBLE(asdecimal=True), nullable=True, comment='测试保证金'),
    sa.Column('CommissionRatio', mysql.DOUBLE(asdecimal=True), nullable=True, comment='交易佣金分成'),
    sa.Column('ExchangeRate', mysql.DOUBLE(asdecimal=True), nullable=True, comment='人民币与股币兑换'),
    sa.Column('MemberPrefix', mysql.VARCHAR(length=255), nullable=True, comment='会员账号前缀'),
    sa.Column('MemberMaximum', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=True, comment='可创建会员数量限制'),
    sa.Column('Bank', mysql.VARCHAR(length=255), nullable=True, comment='收款银行'),
    sa.Column('BankAccount', mysql.VARCHAR(length=30), nullable=True, comment='银行账号'),
    sa.Column('Cardholder', mysql.VARCHAR(length=30), nullable=True, comment='银行账户名'),
    sa.Column('WithdrawPassWord', mysql.VARCHAR(length=30), nullable=True, comment='取款密码'),
    sa.Column('Type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='账户类型，正式，测试，其他'),
    sa.Column('AgentLevel', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=False, comment='代理用户等级（甄别多级代理）'),
    sa.Column('Lock', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='锁定'),
    sa.ForeignKeyConstraint(['ID'], ['sm_user.ID'], name='FK_Reference_2', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ID'),
    comment='代理表',
    mysql_comment='代理表',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('sm_user_log',
    sa.Column('ID', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=True, nullable=False, comment='日志id'),
    sa.Column('UserID', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=True, comment='操作者'),
    sa.Column('Type', mysql.VARCHAR(length=50), nullable=True, comment='操作类型'),
    sa.Column('Model', mysql.VARCHAR(length=50), nullable=True, comment='操作模块'),
    sa.Column('Time', mysql.DATETIME(), nullable=False),
    sa.Column('Note', mysql.VARCHAR(length=255), nullable=True, comment='操作记录'),
    sa.ForeignKeyConstraint(['UserID'], ['sm_user.ID'], name='FK_Reference_11', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('ID'),
    comment='用户日志记录',
    mysql_comment='用户日志记录',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('sm_user_member',
    sa.Column('ID', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=False, comment='会员ID'),
    sa.Column('AgentID', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=False, comment='归属的代理账号id'),
    sa.Column('ClerkID', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=True, comment='业务员ID'),
    sa.Column('CustomerName', mysql.VARCHAR(length=30), nullable=True, comment='客户姓名'),
    sa.Column('Margin', mysql.DOUBLE(asdecimal=True), nullable=True, comment='保证金'),
    sa.Column('PhoneNum', mysql.VARCHAR(length=20), nullable=True, comment='手机号码'),
    sa.Column('BuyFeeRate', mysql.DOUBLE(asdecimal=True), nullable=True, comment='买入手续费'),
    sa.Column('SellFeeRate', mysql.DOUBLE(asdecimal=True), nullable=True, comment='卖出手续费'),
    sa.Column('RiseFallSpreadRate', mysql.DOUBLE(asdecimal=True), nullable=True, comment='涨跌点差率'),
    sa.Column('Bank', mysql.VARCHAR(length=255), nullable=True, comment='收款银行'),
    sa.Column('BankAccount', mysql.VARCHAR(length=30), nullable=True, comment='银行账户'),
    sa.Column('Cardholder', mysql.VARCHAR(length=30), nullable=True, comment='银行账户名'),
    sa.Column('OpeningBank', mysql.VARCHAR(length=30), nullable=True, comment='开户行'),
    sa.Column('WithdrawPassWord', mysql.VARCHAR(length=30), nullable=True, comment='取款密码'),
    sa.Column('EmailAddress', mysql.VARCHAR(length=50), nullable=True, comment='邮箱地址'),
    sa.Column('QQNum', mysql.VARCHAR(length=20), nullable=True, comment='QQ号'),
    sa.Column('Type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='账户类型，正式，测试，其他'),
    sa.Column('Lock', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='是否锁定'),
    sa.ForeignKeyConstraint(['AgentID'], ['sm_user_agent.ID'], name='FK_Reference_7'),
    sa.ForeignKeyConstraint(['ClerkID'], ['sm_clerk.ID'], name='FK_Reference_6', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ID'], ['sm_user.ID'], name='FK_Reference_3', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ID'),
    comment='会员表',
    mysql_comment='会员表',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('sm_user_role',
    sa.Column('ID', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=True, nullable=False, comment='用户类型id'),
    sa.Column('Name', mysql.CHAR(length=50), nullable=False, comment='名称'),
    sa.Column('Description', mysql.VARCHAR(length=255), nullable=True, comment='描述'),
    sa.PrimaryKeyConstraint('ID'),
    comment='用户组表',
    mysql_comment='用户组表',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('sm_stock_para',
    sa.Column('TickerSymbol', mysql.VARCHAR(length=30), nullable=False, comment='股票代码'),
    sa.Column('Name', mysql.VARCHAR(length=50), nullable=True, comment='股票名称'),
    sa.Column('Abridge', mysql.VARCHAR(length=30), nullable=True, comment='拼音缩写'),
    sa.Column('Type', mysql.VARCHAR(length=30), nullable=True, comment='股票类型'),
    sa.Column('BuyByBullish', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True, comment='可买多'),
    sa.Column('BuyByBearish', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True, comment='可买空'),
    sa.Column('Buiable', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True, comment='可买的'),
    sa.Column('Sellable', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True, comment='可卖的'),
    sa.Column('Close', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='关盘'),
    sa.Column('Suspend', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='停牌'),
    sa.Column('SuspendTime', mysql.DATETIME(), nullable=True),
    sa.Column('Forbidden', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='禁用'),
    sa.Column('Note', mysql.VARCHAR(length=255), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('TickerSymbol'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
